### ISSUE TITLE
秘密鍵の管理方法

### ISSUE THREAD

**Issue by cry999** [commets/builder#1]
秘密鍵の共有方法をどうするか決めたいです。

自動化・バージョン管理などがなるべく容易にできる方法がほしいです。

**Comment by nrhrhysd616** [comment]
秘密鍵というのは、SSHアクセスのための秘密鍵という認識で大丈夫ですか？

**Comment by cry999** [comment]
>>>
秘密鍵というのは、SSHアクセスのための秘密鍵という認識で大丈夫ですか？
>>>

そうです。

kms ちょっと調べてみましたが、kms で暗号化の鍵管理して秘密鍵はそれを使って暗号化して git で管理、みたいな記事をちらほら見かけたのでそうしようかと思います。ありがとうございます。

**Comment by nrhrhysd616** [comment]
👌
